name: Validate

on:
  - push
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.40.0
      - name: validate-breaking-changes
        run: REPO=https://github.com/$GITHUB_REPOSITORY.git; buf breaking --against $REPO
