name: Validate

on:
  - push
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.3.1
        with:
          version: 0.54.1
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v0.4.0
        with:
          against: "https://github.com/$GITHUB_REPOSITORY.git#branch=main"
